# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaceAutoComplete' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlaceAutoComplete



pod 'GoogleMaps', '~> 2.1'
pod 'GooglePlacePicker', '~> 2.1'
pod 'GooglePlaces', '~> 2.1'
end
  target 'PlaceAutoCompleteTests' do
    inherit! :search_paths
    # Pods for testing
 

end
