# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KobeSample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KobeSample

pod 'AFNetworking', '~> 3.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'GoogleMaps', '~> 2.1'

end
