# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'GoogleMaps', '~> 2.1'
pod 'GooglePlaces', '~> 2.1'
  # Pods for GoogleMapDemo
end

  target 'GoogleMapDemoTests' do
    inherit! :search_paths
    # Pods for testing
 

end
