# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookIntegrationDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookIntegrationDemo

pod 'AFNetworking', '~> 3.1'
pod 'MBProgressHUD', '~> 1.0'
 end
  target 'FacebookIntegrationDemoTests' do
    inherit! :search_paths
    # Pods for testing
 

end
